### ISSUE TITLE
Main方法的描述部分有问题

### ISSUE THREAD

**Issue by joinmouse** [hcsp/fix-divide-bug#2]
![image](https://user-images.githubusercontent.com/18349016/58972307-db701500-87ef-11e9-9863-8e0787296968.png)

描述部分出错了
`2/1 = 1.0` 应该是`2/1 = 2.0`
2/1的正确结果是0.5

**Comment by blindpirate** [comment]
感谢反馈！

**Comment by blindpirate** [comment]
Closed by https://github.com/hcsp/fix-divide-bug/commit/ff8fa77e6e0b1a3f30d2837bc38ad20cc874bb93
